version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    image: dojo-log-api
    volumes:
      - .:/usr/src/app
    container_name: dojo_log_api
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    command: npm run dev

  db:
    image: postgres:13
    container_name: dojo_log_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dojolog
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '2345:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes: 
  postgres:

    